### ISSUE TITLE
Support for Cocoapods

### ISSUE THREAD

**Issue by seppelandrio** [czechboy0/Redbird#34]
Hi czechboy0,

is it possible to support cocoapods as package manager too?

That would be great.
Seppelandrio

**Comment by czechboy0** [comment]
Hi @seppelandrio,

I'm not planning to do that at this moment, as the version of Swift required by Redbird changes with Swift 3 getting finalized, but with CocoaPods most people use the standard Xcode Swift version. 

If you'd like to use Redbird in your project, manually clone it (and also Socks, its dependency) locally. I'll consider adding CocoaPods support when Swift 3 is released.

**Comment by seppelandrio** [comment]
Hi,

now Swift 3 has been officially released. Can you please add CocoaPods? It would help me a lot.

Greets.
Seppelandrio
